---
- name: html directory
  file:
    path: /var/www/ma.xprettyjohns/html
    state: directory
- name: download release
  unarchive:
    src: "https://github.com/heshoots/site/releases/download/{{ maxprettyjohns_release }}/maxprettyjohns.tar.gz"
    dest: /var/www/ma.xprettyjohns/html
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify:
    - restart caddy
