---
- name: html directory
  file:
    path: /var/www/ma.xprettyjohns/html
    state: directory
- name: download release
  unarchive:
    src: "https://github.com/quorauk/ma.xprettyjohns.com/releases/download/{{ maxprettyjohns_release }}/ma.xprettyjohns.com.tgz"
    dest: /var/www/ma.xprettyjohns/html
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify:
    - restart caddy
