---
- name: discordbot bin directory
  file:
    path: "{{ discordbot_app_directory }}"
    state: directory
- name: discordbot config directory
  file:
    path: "{{ discordbot_conf_directory }}"
    state: directory
- name: pull smbfapi binary
  get_url:
    url: "https://github.com/heshoots/discordbot/releases/download/{{ discordbot_release }}/discordbot"
    dest: "{{ discordbot_app_directory }}/discordbot"
    mode: 775
    checksum: "{{ discordbot_checksum }}"
- name: move systemd unit
  copy:
    src: ../files/discordbot.service
    dest: /etc/systemd/system/discordbot.service
- name: move environmentFile
  copy:
    src: ../files/env
    dest: "{{ discordbot_conf_directory }}/env"
    decrypt: yes
- name: move config
  copy:
    src: ../files/config.yaml
    dest: "{{ discordbot_conf_directory }}/config.yaml"
- name: discordbot.service started
  service:
    daemon_reload: yes
    name: discordbot 
    enabled: yes
    state: restarted
