---
- name: install redis
  apt:
    name: redis-server
    state: present
- name: discordbot bin directory
  file:
    path: "{{ cholibot_app_directory }}"
    state: directory
- name: cholibot config directory
  file:
    path: "{{ cholibot_conf_directory }}"
    state: directory
- name: pull cholibot binary
  get_url:
    url: "https://github.com/quorauk/cholibot/releases/download/{{ cholibot_release }}/cholibot"
    dest: "{{ cholibot_app_directory }}/cholibot"
    mode: 775
    checksum: "{{ cholibot_checksum }}"
- name: move systemd unit
  template:
    src: ../files/cholibot.service
    dest: "/etc/systemd/system/cholibot-{{ cholibot_environment }}.service"
- name: move config file
  copy:
    src: "../files/{{ cholibot_environment }}.yaml"
    dest: "{{ cholibot_conf_directory }}/{{ cholibot_environment }}.yaml"
    decrypt: yes
- name: cholibot.service started
  service:
    daemon_reload: yes
    name: "cholibot-{{ cholibot_environment }}"
    enabled: yes
    state: restarted
- name: cholibot config directory
  file:
    path: ../files/nginx-config
    dest: "/etc/nginx/sites-enabled/bot.fightinggame.community"
  notify:
    - restart nginx
