---
- name: html directory
  file:
    path: /var/www/superminerbattle.farm/html
    state: directory
- name: download release
  unarchive:
    src: "https://github.com/quorauk/superminerbattle.farm/releases/download/{{ smbf_release }}/superminerbattle.farm.tgz"
    dest: /var/www/superminerbattle.farm/html
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify:
    - restart caddy
