---
- hosts: tag_webserver
  remote_user: heshoots9999
  become: yes
  vars:
    cholibot_conf_directory: /opt/cholibot-production/config
    cholibot_app_directory: /opt/cholibot-production/bin
    cholibot_environment: production
    cholibot_checksum: sha256:cef830537e8ec2a14832dae7d384cd703fffe416f23028a18c9f1404c2cefab4
    cholibot_release: v0.0.5
  roles:
    - cholibot
