---
- hosts: tag_webserver
  remote_user: heshoots9999
  become: yes
  vars:
    cholibot_conf_directory: /opt/cholibot-production/config
    cholibot_app_directory: /opt/cholibot-production/bin
    cholibot_environment: production
    cholibot_release: v0.0.7
    cholibot_checksum: sha256:ef6104c343794a86bdefc4b1e502115400d613589eac1521870583c39d5226d3
  roles:
    - cholibot
