---
- hosts: tag_webserver
  user: heshoots9999
  become: yes
  roles:
    - ma.xprettyjohns
    - superminerbattle.farm
    - smbf-api
    - caddy
  handlers:
  - name: restart smbfapi
    service: name=smbfapi state=restarted
  - name: restart caddy
    service: name=caddy state=restarted
